apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../local/infrastructure.yaml
patches:
  - target:
      kind: Deployment
      name: conexao-solidaria-redis
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: conexao-solidaria-redis
      spec:
        template:
          spec:
            volumes:
              - name: data
                persistentVolumeClaim: null
                emptyDir:
                  sizeLimit: 1Gi
  - target:
      kind: PersistentVolumeClaim
      name: conexao-solidaria-redis
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: conexao-solidaria-redis
      $patch: delete
