<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="MassTransit.TestFramework" Version="8.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Contracts\ConexaoSolidaria.Contracts\ConexaoSolidaria.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Services\Campaigns\ConexaoSolidaria.Campaigns.Api\ConexaoSolidaria.Campaigns.Api.csproj" />
    <ProjectReference Include="..\..\src\Services\Campaigns\ConexaoSolidaria.Campaigns.Data\ConexaoSolidaria.Campaigns.Data.csproj" />
    <ProjectReference Include="..\..\src\Services\Campaigns\ConexaoSolidaria.Campaigns.Infrastructure\ConexaoSolidaria.Campaigns.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Services\Campaigns\ConexaoSolidaria.Campaigns.Worker\ConexaoSolidaria.Campaigns.Worker.csproj" />
    <ProjectReference Include="..\..\src\Services\Donations\ConexaoSolidaria.Donations.Api\ConexaoSolidaria.Donations.Api.csproj" />
    <ProjectReference Include="..\..\src\Services\Payments\ConexaoSolidaria.Payments.Api\ConexaoSolidaria.Payments.Api.csproj" />
  </ItemGroup>

</Project>
