apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "conexao-solidaria.fullname" . }}-web
  labels:
    {{- include "conexao-solidaria.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "conexao-solidaria.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "conexao-solidaria.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ include "conexao-solidaria.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
          envFrom:
            - configMapRef:
                name: {{ include "conexao-solidaria.fullname" . }}-web
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.web.probes.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.web.probes.readinessPath }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.web.probes.livenessPath }}
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          {{- end }}
