global:
  environment: local
  cloudProvider: docker-desktop

image:
  registry: ""
  tag: latest
  pullPolicy: IfNotPresent

components:
  web:
    replicaCount: 2
    service:
      type: ClusterIP
    env:
      ASPNETCORE_ENVIRONMENT: Development
      DemoAccess__Enabled: "true"
  gateway:
    replicaCount: 2
    service:
      type: ClusterIP
    env:
      ASPNETCORE_ENVIRONMENT: Development
  identity-api:
    env:
      ASPNETCORE_ENVIRONMENT: Development
  campaigns-api:
    env:
      ASPNETCORE_ENVIRONMENT: Development
  payments-api:
    env:
      ASPNETCORE_ENVIRONMENT: Development
  donations-worker:
    env:
      ASPNETCORE_ENVIRONMENT: Development
  audit-api:
    env:
      ASPNETCORE_ENVIRONMENT: Development
  knowledge-api:
    env:
      ASPNETCORE_ENVIRONMENT: Development

ingress:
  enabled: false

topologySpreadConstraints:
  enabled: false
